### ISSUE TITLE
Missing hash produce error

### ISSUE THREAD

**Issue by zslabs** [bendc/anchor-scroll#12]
Obviously more of a user error scenario here, but if you attempt to link to an ID that is not on the page, you get the following error: `Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null` What do you think about not attempting to move anywhere at that point if you can't find the selector?

Also, I'd like to suggest adding a single # with no ID should scroll up to the top of the page as a native # would.

**Comment by bendc** [comment]
Makes sense, will fix.

**Comment by bendc** [comment]
Fixed!

**Comment by zslabs** [comment]
Looks good, thanks!
