### ISSUE TITLE
mention ES6 in the README

### ISSUE THREAD

**Issue by callmecavs** [bendc/anchor-scroll#13]
Looks like the code is running through some kind of transpilation step, because the fat arrow functions are missing from the `.min` file, and the `const` declarations are converted to `var`. is it possible that the minifier is smart enough to remove them?

Anyways, the `Map` object and the `Array.from` method - both of which are part of the ES6 spec - make an appearance in the `.min` file.  Perhaps this should be noted in the README?

**Comment by bendc** [comment]
The minified file has actually been transpiled first ;) Anyway, I'm peaceful for now targeting Edge only but I'll add a note in the readme if people seem confused.
