### ISSUE TITLE
Junk when  scroll

### ISSUE THREAD

**Issue by samosale** [bendc/anchor-scroll#18]
Have a considerable  junk on scrolling all the way down to the bottom of the page.

**Comment by bendc** [comment]
On which page?

**Comment by samosale** [comment]
samosale.github.io

**Comment by bendc** [comment]
I'm afraid it doesn't have anything to do with the library, you have scrolling perf issues on Chrome even when you scroll manually.

**Comment by samosale** [comment]
Ok,did not know, tnx for tips.
