### ISSUE TITLE
Exception when there is no "a.scroll" element

### ISSUE THREAD

**Issue by dcorb** [bendc/anchor-scroll#21]
In pages where there is no anchors:
`Uncaught TypeError: Cannot read property 'addEventListener' of null`
In Chrome
I guess, it needs a if (link) or if (links) somewhere https://github.com/bendc/anchor-scroll/blob/master/scroll.js#L57

**Comment by dcorb** [comment]
Fixed in the meanwhile like this:
```
const elements = document.querySelectorAll("a.scroll")
if (elements.length) {
  attachHandler(elements));
}
```

**Comment by bendc** [comment]
Fixed, thanks!

**Comment by dcorb** [comment]
That was fast! 👍
