### ISSUE TITLE
Get rid of UA sniffing

### ISSUE THREAD

**Issue by mathiasbynens** [bendc/anchor-scroll#3]
You could get rid of the UA sniffing and go for a more robust, feature-testing-based approach. Here’s how that could work: https://github.com/mathiasbynens/jquery-smooth-scrolling/blob/fba27f86a6b3a8788d1c1b3aa94a951eb9f087dc/jquery.smoothscroll.js#L4-L21

Here’s a simpler version by @dperini: https://gist.github.com/dperini/ac3d921d6a08f10fd10e

**Comment by bendc** [comment]
Done (finally!).

**Comment by mathiasbynens** [comment]
:+1: 2a686d1b9274a45d5bfeb82c9d2e1f6a80e9121a

**Comment by dperini** [comment]
I was adding a couple of edge cases suggested in the Mozilla bug list

    https://bugzilla.mozilla.org/show_bug.cgi?id=1153322

This is to handle 2 body elements in Quirks Mode, or no body element at all (fx: in frameset) etc.
I also added a no-op exit in case of an existing native, there was no such thing at the time I wrote this.

    // use after DOMContentLoaded
    function getScrollingElement() {
            var p = 'scrollingElement',
            r = document.documentElement, b, m;
            if (p in document) return document[p];
            b = document.getElementsByTagName('body'),
            m = document.compatMode.indexOf('CSS1') == 0;
            if (b.length == 0) return r; else if (!m) return b[0];
            return r.scrollHeight > b[0].scrollHeight && m ? r : b[0];
    }

Check it out and please report defects :)

Have fun !
